using System.Text.Json;
using System.Text.Json.Serialization;
using Foxfire.Core;

namespace Foxfire.Core.Tests;

/// <summary>
/// The server's ladder maths, checked against the desktop's, case for case.
///
/// Foxfire computes LP twice now, in two languages, and shows both answers to
/// the same person — so the two agreeing is not a nicety, it is the feature.
/// Porting the desktop's test cases proves somebody transcribed the assertions
/// faithfully; it does not prove the implementations agree, because the same
/// person wrote both suites and both could be wrong the same way.
///
/// So the inputs and the expected outputs come from actually running the
/// TypeScript. fixtures/ladder-corpus.json is generated by
/// apps/desktop/scripts/generate-ladder-corpus.ts and committed; the desktop's
/// own suite asserts it still produces it, and this asserts the server does too.
/// Either side drifting fails here, naming the exact input that disagreed.
///
/// It has already earned this. JavaScript rounds a .5 away from zero and .NET
/// rounds it to the even neighbour, so <see cref="Ladder.RankFromLeaguePoints"/>
/// would have quietly disagreed on every LP value sitting exactly half a
/// division from where somebody started — a case nobody would have thought to
/// write by hand, and one this corpus covers 4,200 times over.
/// </summary>
public class LadderCorpusTests
{
    // Declared before Loaded, and that order is load-bearing: static field
    // initialisers run top to bottom, so a Loaded declared first would call
    // Load() while this was still null and quietly deserialise with the default
    // case-sensitive PascalCase matching — binding every list to null.
    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);

    private static readonly Corpus Loaded = Load();

    /// <summary>
    /// Finds the corpus by walking up from the test assembly.
    ///
    /// The repo root is where the two apps meet, and neither of them owns a file
    /// the other has to read — so it sits between them, and both find it the
    /// same way.
    /// </summary>
    private static Corpus Load()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);

        while (dir is not null)
        {
            var candidate = Path.Combine(dir.FullName, "fixtures", "ladder-corpus.json");
            if (File.Exists(candidate))
            {
                return JsonSerializer.Deserialize<Corpus>(File.ReadAllText(candidate), Json)
                    ?? throw new InvalidOperationException($"{candidate} is empty");
            }

            dir = dir.Parent;
        }

        throw new FileNotFoundException(
            "fixtures/ladder-corpus.json was not found above " + AppContext.BaseDirectory +
            ". Regenerate it with `npx vite-node scripts/generate-ladder-corpus.ts` from apps/desktop.");
    }

    /// <summary>
    /// Reports the first few disagreements rather than only the first.
    ///
    /// A port that is wrong is usually wrong about a whole class of inputs, and
    /// seeing five of them together says which class; seeing one says almost
    /// nothing. The count says how bad it is.
    /// </summary>
    private static void AssertNoDisagreements(List<string> disagreements, int total)
    {
        if (disagreements.Count == 0) return;

        var shown = string.Join("\n  ", disagreements.Take(5));
        Assert.Fail(
            $"{disagreements.Count} of {total} cases disagree with the desktop.\n  {shown}" +
            (disagreements.Count > 5 ? $"\n  … and {disagreements.Count - 5} more" : ""));
    }

    [Fact]
    public void The_corpus_is_big_enough_to_mean_something()
    {
        // Guards against the corpus being regenerated to nothing and every test
        // below passing vacuously.
        Assert.True(Loaded.LadderPosition.Count > 500);
        Assert.True(Loaded.RankMovement.Count > 5_000);
        Assert.True(Loaded.RankFromLeaguePoints.Count > 1_000);
    }

    [Fact]
    public void Ladder_position_agrees_with_the_desktop()
    {
        List<string> wrong = [];

        foreach (var c in Loaded.LadderPosition)
        {
            var mine = Ladder.LadderPosition(c.Rank.ToRank());
            if (mine != c.Position) wrong.Add($"{c.Rank}: desktop {Show(c.Position)}, server {Show(mine)}");
        }

        AssertNoDisagreements(wrong, Loaded.LadderPosition.Count);
    }

    [Fact]
    public void Tier_at_position_agrees_with_the_desktop()
    {
        List<string> wrong = [];

        foreach (var c in Loaded.TierAtPosition)
        {
            var mine = Ladder.TierAtPosition(c.Position).RiotName();
            if (!string.Equals(mine, c.Tier, StringComparison.Ordinal))
            {
                wrong.Add($"{c.Position}: desktop {c.Tier}, server {mine}");
            }
        }

        AssertNoDisagreements(wrong, Loaded.TierAtPosition.Count);
    }

    [Fact]
    public void Rank_movement_agrees_with_the_desktop()
    {
        List<string> wrong = [];

        foreach (var c in Loaded.RankMovement)
        {
            var mine = Ladder.Movement(c.Before.ToRank(), c.After.ToRank());
            var theirs = c.Movement switch
            {
                "promotion" => RankMovement.Promotion,
                "demotion" => RankMovement.Demotion,
                _ => RankMovement.None
            };

            if (mine != theirs) wrong.Add($"{c.Before} -> {c.After}: desktop {c.Movement}, server {mine}");
        }

        AssertNoDisagreements(wrong, Loaded.RankMovement.Count);
    }

    [Fact]
    public void Rank_from_league_points_agrees_with_the_desktop()
    {
        List<string> wrong = [];

        foreach (var c in Loaded.RankFromLeaguePoints)
        {
            var mine = Ladder.RankFromLeaguePoints(c.Before.ToRank(), c.LeaguePoints);
            var theirs = c.Result?.ToRank();

            var same = (mine, theirs) switch
            {
                (null, null) => true,
                (null, _) or (_, null) => false,
                _ => mine.Tier == theirs.Tier
                     && mine.Division == theirs.Division
                     && mine.LeaguePoints == theirs.LeaguePoints
            };

            if (!same)
            {
                wrong.Add($"{c.Before} + {c.LeaguePoints} LP: desktop {Show(theirs)}, server {Show(mine)}");
            }
        }

        AssertNoDisagreements(wrong, Loaded.RankFromLeaguePoints.Count);
    }

    [Fact]
    public void Resets_between_agrees_with_the_desktop()
    {
        var seasons = Loaded.Seasons.Select(s => s.ToSeason()).ToList();
        List<string> wrong = [];

        foreach (var c in Loaded.ResetsBetween)
        {
            var mine = RankedSeasons.ResetsBetween(seasons, c.AfterMs, c.UntilMs);
            if (mine != c.Resets)
            {
                wrong.Add($"({c.AfterMs}, {c.UntilMs}]: desktop {c.Resets}, server {mine}");
            }
        }

        AssertNoDisagreements(wrong, Loaded.ResetsBetween.Count);
    }

    private static string Show(int? value) => value?.ToString() ?? "null";

    private static string Show(Rank? rank) =>
        rank is null
            ? "null"
            : $"{rank.Tier?.RiotName() ?? "null"} {rank.Division?.RiotName() ?? "null"} {rank.LeaguePoints}";

    /* ---------------------------------------------------------------- */
    /* the shapes on disk                                               */
    /* ---------------------------------------------------------------- */

    internal sealed record Corpus(
        IReadOnlyList<LadderPositionCase> LadderPosition,
        IReadOnlyList<TierAtPositionCase> TierAtPosition,
        IReadOnlyList<MovementCase> RankMovement,
        IReadOnlyList<FromLeaguePointsCase> RankFromLeaguePoints,
        IReadOnlyList<SeasonDto> Seasons,
        IReadOnlyList<ResetCase> ResetsBetween);

    /// <summary>
    /// The desktop calls the division `rank`, which is why this maps rather than
    /// binding straight onto <see cref="Foxfire.Core.Rank"/>.
    /// </summary>
    internal sealed record RankDto(
        string? Tier,
        [property: JsonPropertyName("rank")] string? Division,
        int? LeaguePoints)
    {
        /// <summary>
        /// The corpus stays strings, and the parse happens here.
        ///
        /// Which is also a case the corpus tests: it carries a NOT_A_TIER, and
        /// the desktop answers null for it because indexOf returns -1. This
        /// server answers null because FromRiotName does. The agreement those
        /// cases assert is therefore a real one, not an artefact of both sides
        /// being handed something they could parse.
        /// </summary>
        public Rank ToRank() =>
            new(RankTiers.FromRiotName(Tier), RankDivisions.FromRiotName(Division), LeaguePoints);

        public override string ToString() => $"{Tier ?? "null"} {Division ?? "null"} {Show(LeaguePoints)}";
    }

    internal sealed record LadderPositionCase(RankDto Rank, int? Position);

    internal sealed record TierAtPositionCase(int Position, string Tier);

    internal sealed record MovementCase(RankDto Before, RankDto After, string Movement);

    internal sealed record FromLeaguePointsCase(RankDto Before, int LeaguePoints, RankDto? Result);

    internal sealed record SeasonDto(int Id, string Label, long StartsAt, bool IsPreseason, bool ResetsRank)
    {
        public Season ToSeason() => new(Id, Label, StartsAt, IsPreseason, ResetsRank);
    }

    internal sealed record ResetCase(long AfterMs, long UntilMs, bool Resets);
}
