using System.Text.Json;
using System.Text.Json.Serialization;
using Foxfire.Core;

namespace Foxfire.Core.Tests;

/// <summary>
/// The server's thirty-day rank trend, checked against the desktop's, case for case.
///
/// The profile's graph is drawn from <see cref="RankTrends"/> on a server and
/// from packages/core/src/rules/rankTrend.ts on a desktop that has none, and the
/// same person can see both. fixtures/rank-trend-corpus.json is generated by
/// running the TypeScript (packages/core/scripts/generate-rank-trend-corpus.ts),
/// the TypeScript suite asserts it still produces it, and this asserts the port
/// does too — so the two agree because they were run, not because somebody
/// transcribed the same assertions twice.
/// </summary>
public class RankTrendCorpusTests
{
    // Declared before Loaded, and that order is load-bearing — see LadderCorpusTests.
    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);

    private static readonly Corpus Loaded = Load();

    private static Corpus Load()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);

        while (dir is not null)
        {
            var candidate = Path.Combine(dir.FullName, "fixtures", "rank-trend-corpus.json");
            if (File.Exists(candidate))
            {
                return JsonSerializer.Deserialize<Corpus>(File.ReadAllText(candidate), Json)
                    ?? throw new InvalidOperationException($"{candidate} is empty");
            }

            dir = dir.Parent;
        }

        throw new FileNotFoundException(
            "fixtures/rank-trend-corpus.json was not found above " + AppContext.BaseDirectory +
            ". Regenerate it with `npm run generate-trend-corpus` from packages/core.");
    }

    [Fact]
    public void The_corpus_is_big_enough_to_mean_something()
    {
        Assert.True(Loaded.Cases.Count > 50);
        Assert.True(Loaded.Cases.Sum(c => c.Trend.Points.Count) > 1_000);
        Assert.Contains(Loaded.Cases, c => c.Trend.NetLp is null && c.Trend.Points.Count > 0);
    }

    [Fact]
    public void The_trend_agrees_with_the_desktop()
    {
        var seasons = Loaded.Seasons.Select(s => s.ToSeason()).ToList();
        List<string> wrong = [];

        foreach (var c in Loaded.Cases)
        {
            var mine = RankTrends.Of([.. c.Readings.Select(r => r.ToReading())], seasons, c.Now);
            var disagreement = Compare(mine, c.Trend);
            if (disagreement is not null) wrong.Add($"{c.Name}: {disagreement}");
        }

        if (wrong.Count == 0) return;

        var shown = string.Join("\n  ", wrong.Take(5));
        Assert.Fail(
            $"{wrong.Count} of {Loaded.Cases.Count} cases disagree with the desktop.\n  {shown}" +
            (wrong.Count > 5 ? $"\n  … and {wrong.Count - 5} more" : ""));
    }

    /// <summary>The first thing that differs, or null when nothing does.</summary>
    private static string? Compare(RankTrend mine, TrendDto theirs)
    {
        if (mine.From != theirs.From || mine.To != theirs.To)
        {
            return $"window desktop {theirs.From}..{theirs.To}, server {mine.From}..{mine.To}";
        }

        if (mine.NetLp != theirs.NetLp) return $"netLp desktop {Show(theirs.NetLp)}, server {Show(mine.NetLp)}";

        if (mine.Points.Count != theirs.Points.Count)
        {
            return $"desktop has {theirs.Points.Count} points, server {mine.Points.Count}";
        }

        for (var i = 0; i < mine.Points.Count; i++)
        {
            var server = PointDto.Of(mine.Points[i]);
            if (server != theirs.Points[i]) return $"point {i}: desktop {theirs.Points[i]}, server {server}";
        }

        return null;
    }

    private static string Show(int? value) => value?.ToString() ?? "null";

    /* ---------------------------------------------------------------- */
    /* the shapes on disk                                               */
    /* ---------------------------------------------------------------- */

    internal sealed record Corpus(IReadOnlyList<SeasonDto> Seasons, IReadOnlyList<CaseDto> Cases);

    internal sealed record CaseDto(string Name, long Now, IReadOnlyList<ReadingDto> Readings, TrendDto Trend);

    internal sealed record TrendDto(long From, long To, IReadOnlyList<PointDto> Points, int? NetLp);

    /// <summary>A reading as the desktop writes one: the division is `rank`, and the queue is implied.</summary>
    internal sealed record ReadingDto(
        string? Tier,
        [property: JsonPropertyName("rank")] string? Division,
        int? LeaguePoints,
        int? LadderPosition,
        long CapturedAt)
    {
        public RankReading ToReading() => new(
            RankedQueue.SoloDuo,
            RankTiers.FromRiotName(Tier),
            RankDivisions.FromRiotName(Division),
            LeaguePoints,
            Wins: null,
            Losses: null,
            LadderPosition,
            Source: "lcu",
            CapturedAt);
    }

    internal sealed record PointDto(
        long At,
        string? Tier,
        [property: JsonPropertyName("rank")] string? Division,
        int? LeaguePoints,
        int? LadderPosition,
        int? SeasonId,
        long CapturedAt)
    {
        public static PointDto Of(RankTrendPoint point) => new(
            point.At,
            point.Reading.Tier?.RiotName(),
            point.Reading.Division?.RiotName(),
            point.Reading.LeaguePoints,
            point.Reading.LadderPosition,
            point.SeasonId,
            point.Reading.CapturedAt);
    }

    internal sealed record SeasonDto(int Id, string Label, long StartsAt, bool IsPreseason, bool ResetsRank)
    {
        public Season ToSeason() => new(Id, Label, StartsAt, IsPreseason, ResetsRank);
    }
}
