import type { SVGProps } from 'react'
import mark from '../assets/logoMark.json'

/**
 * The Foxfire mark: three wisps circling an empty centre.
 *
 * Foxfire is the light that hangs over rotting wood in a forest, and the name
 * of the flames Ahri carries. Neither is a fox, and neither is drawn here — an
 * animal silhouette costs more detail than 16px has to give, and a fox head in
 * warm colours is a Firefox logo whether or not that was the intention. Three
 * wisps on an orbit say the same thing and survive being small.
 *
 * Filled rather than stroked, which is the exception documented in icons.tsx
 * for Coin, Skull and Record: a 2px outline on the 24 grid closes up into a
 * smudge below about 11px, and the tray asks for exactly 16. A teardrop is a
 * solid shape anyway — outlining it would be drawing the wrong thing.
 *
 * Each wisp's tail follows the orbit itself rather than flying off along the
 * tangent, which is what makes three separate shapes read as one rotation.
 *
 * The geometry lives in @shared/logoMark.json because scripts/make-icon.mjs
 * draws the same three paths into the .ico and the tray PNG. The tray icon used
 * to be a base64 blob pasted in by hand next to a comment admitting it had to
 * match the build script; one file both can read is what stops that recurring.
 *
 * That file is generated by scripts/make-mark.mjs and should not be hand-edited
 * — the outline is a sampled offset curve, not something to nudge by eye. To
 * change the mark, edit the constants there, re-run `npm run make-mark`, then
 * `npm run make-icon`.
 */
export function Logo(props: SVGProps<SVGSVGElement>): JSX.Element {
  return (
    <svg
      width="16"
      height="16"
      viewBox={`0 0 ${mark.grid} ${mark.grid}`}
      fill="currentColor"
      stroke="none"
      aria-hidden
      {...props}
    >
      {mark.placements.map((placement) => (
        <path key={placement} d={mark.wisp} transform={placement} />
      ))}
    </svg>
  )
}
