/**
 * Writes the golden corpus that pins the TypeScript ladder and LP maths — the
 * one copy the desktop and the web client both run — to the server's.
 *
 * Run with: npm run generate-corpus   (from packages/core)
 *
 * The problem this solves is that Foxfire now computes LP twice, in two
 * languages, and shows both answers to the same person. Porting the test cases
 * across proves somebody transcribed the assertions; it does not prove the two
 * implementations agree, because both suites were written by whoever wrote the
 * code. What proves it is running the same inputs through both and comparing —
 * which is what this generates the inputs and expected outputs for.
 *
 * The output is committed. From then on the TypeScript suite asserts it still
 * produces the corpus, the C# suite asserts it produces the corpus too, and
 * either implementation drifting fails immediately with the exact input that
 * disagreed. It also catches the failure nobody would think to write a case
 * for: JavaScript rounds a .5 up and .NET rounds it to even, so the two would
 * have silently disagreed on a whole class of hand-entered LP values.
 *
 * Inputs are enumerated rather than random. A fixed corpus that is regenerated
 * deliberately is worth more than a fuzzer whose failures cannot be reproduced.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  ladderPosition,
  rankFromLeaguePoints,
  rankMovement,
  tierAtPosition,
  ALL_TIERS,
  DIVISIONS
} from '../src/rules/ladder'
import { resetsBetween } from '../src/rules/seasons'
import type { Season } from '../src/types'

const HERE = dirname(fileURLToPath(import.meta.url))
const OUT = join(HERE, '..', '..', '..', 'fixtures', 'ladder-corpus.json')

/** Tiers, plus the two ways a tier can be unusable. */
const TIERS: Array<string | null> = [...ALL_TIERS, null, 'NOT_A_TIER']

/** Divisions, plus absent — which is what an apex rank and a broken row both look like. */
const DIVS: Array<string | null> = [...DIVISIONS, null]

/**
 * LP values worth trying.
 *
 * The boundaries are where the arithmetic is interesting: 0 and 100 are
 * division edges, 50 is the exact midpoint that makes the division estimate
 * land on a .5, and the apex values run past 100 where LP stops wrapping.
 */
const LPS: Array<number | null> = [0, 1, 50, 75, 99, 100, 250, 500, 1200, null]

interface RankInput {
  tier: string | null
  rank: string | null
  leaguePoints: number | null
}

function ranks(): RankInput[] {
  const out: RankInput[] = []
  for (const tier of TIERS) {
    for (const rank of DIVS) {
      for (const leaguePoints of LPS) {
        out.push({ tier, rank, leaguePoints })
      }
    }
  }
  return out
}

const RANKS = ranks()

/**
 * Movement is sampled on both sides rather than taken as the full N² product.
 *
 * The full matrix is 51,600 cases and fourteen megabytes of committed
 * fixture, for logic that is two index comparisons. What matters is that every
 * tier, every division and every unusable value appears on both sides, which
 * strided sampling keeps. The exhaustive treatment is spent where it buys
 * something instead: ladderPosition, and rankFromLeaguePoints, where the two
 * languages round differently.
 */
const MOVEMENT_BEFORE = RANKS.filter((_, i) => i % 5 === 0)
const MOVEMENT_PARTNERS = RANKS.filter((_, i) => i % 13 === 0)

const SEASONS: Season[] = [
  { id: 1, label: 'Season 2026', startsAt: new Date(2026, 0, 8).getTime(), isPreseason: false, resetsRank: true },
  { id: 2, label: 'Preseason 2027', startsAt: new Date(2026, 11, 22).getTime(), isPreseason: true, resetsRank: false },
  { id: 3, label: 'Season 2027', startsAt: new Date(2027, 0, 8).getTime(), isPreseason: false, resetsRank: true }
]

/** Moments either side of, and exactly on, each boundary. */
function resetProbes(): Array<{ afterMs: number; untilMs: number; resets: boolean }> {
  const marks = SEASONS.flatMap((s) => [s.startsAt - 1, s.startsAt, s.startsAt + 1])
  const out: Array<{ afterMs: number; untilMs: number; resets: boolean }> = []

  for (const afterMs of marks) {
    for (const untilMs of marks) {
      if (untilMs < afterMs) continue
      out.push({ afterMs, untilMs, resets: resetsBetween(SEASONS, afterMs, untilMs) })
    }
  }

  return out
}

const corpus = {
  note:
    'Generated by packages/core/scripts/generate-ladder-corpus.ts. Pins the desktop and the ' +
    'server to the same ladder arithmetic. Regenerate deliberately, never to make a test pass.',

  ladderPosition: RANKS.map((rank) => ({ rank, position: ladderPosition(rank) })),

  tierAtPosition: [0, 1, 399, 400, 1200, 1250, 1599, 2799, 2800, 2801, 4000].map((position) => ({
    position,
    tier: tierAtPosition(position)
  })),

  rankMovement: MOVEMENT_BEFORE.flatMap((before) =>
    MOVEMENT_PARTNERS.map((after) => ({ before, after, movement: rankMovement(before, after) }))
  ),

  rankFromLeaguePoints: RANKS.flatMap((before) =>
    [0, 3, 50, 68, 88, 91, 99].map((leaguePoints) => ({
      before,
      leaguePoints,
      result: rankFromLeaguePoints(before, leaguePoints)
    }))
  ),

  seasons: SEASONS,
  resetsBetween: resetProbes()
}

mkdirSync(dirname(OUT), { recursive: true })
// Compact rather than pretty-printed. This is committed, it is machine-read at
// both ends, and indentation is most of its weight.
writeFileSync(OUT, `${JSON.stringify(corpus)}\n`)

const counts = {
  ladderPosition: corpus.ladderPosition.length,
  tierAtPosition: corpus.tierAtPosition.length,
  rankMovement: corpus.rankMovement.length,
  rankFromLeaguePoints: corpus.rankFromLeaguePoints.length,
  resetsBetween: corpus.resetsBetween.length
}

console.log(`Wrote ${OUT}`)
console.log(counts)
console.log(`total cases: ${Object.values(counts).reduce((a, b) => a + b, 0)}`)
