// <auto-generated />
using System;
using Foxfire.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Foxfire.Data.Migrations
{
    [DbContext(typeof(FoxfireDbContext))]
    [Migration("20260926163556_TelemetryRollups")]
    partial class TelemetryRollups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Foxfire.Data.Entities.ChampionMastery", b =>
                {
                    b.Property<Guid>("RiotAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChampionId")
                        .HasColumnType("int");

                    b.Property<int?>("ChampionLevel")
                        .HasColumnType("int");

                    b.Property<int?>("ChampionPoints")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("LastPlayTime")
                        .HasColumnType("bigint");

                    b.HasKey("RiotAccountId", "ChampionId");

                    b.ToTable("ChampionMasteries");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.FoxfireUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Foxfire.Data.Entities.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("RedeemedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Email");

                    b.HasIndex("RedeemedByUserId");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.LeagueEntry", b =>
                {
                    b.Property<Guid>("RiotAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QueueType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Division")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("LeaguePoints")
                        .HasColumnType("int");

                    b.Property<int?>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("Tier")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("Wins")
                        .HasColumnType("int");

                    b.HasKey("RiotAccountId", "QueueType");

                    b.ToTable("LeagueEntries");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.Match", b =>
                {
                    b.Property<string>("MatchId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("GameCreation")
                        .HasColumnType("bigint");

                    b.Property<int>("GameDuration")
                        .HasColumnType("int");

                    b.Property<string>("GameMode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("GameType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PlatformId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int?>("QueueId")
                        .HasColumnType("int");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MatchId");

                    b.HasIndex("GameCreation");

                    b.HasIndex("QueueId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.MatchParticipant", b =>
                {
                    b.Property<string>("MatchId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Puuid")
                        .HasMaxLength(78)
                        .HasColumnType("nvarchar(78)");

                    b.Property<int?>("Assists")
                        .HasColumnType("int");

                    b.Property<int?>("ChampLevel")
                        .HasColumnType("int");

                    b.Property<int>("ChampionId")
                        .HasColumnType("int");

                    b.Property<string>("ChampionName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("Cs")
                        .HasColumnType("int");

                    b.Property<int?>("DamageDealtToChampions")
                        .HasColumnType("int");

                    b.Property<int?>("DamageTaken")
                        .HasColumnType("int");

                    b.Property<int?>("Deaths")
                        .HasColumnType("int");

                    b.Property<bool>("GameEndedInEarlySurrender")
                        .HasColumnType("bit");

                    b.Property<string>("GameName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("GoldEarned")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Items")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ItemsJson");

                    b.Property<int?>("Kills")
                        .HasColumnType("int");

                    b.Property<int?>("LargestMultiKill")
                        .HasColumnType("int");

                    b.Property<string>("PerksJson")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("RoleBoundItem")
                        .HasColumnType("int");

                    b.Property<int?>("Summoner1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Summoner2Id")
                        .HasColumnType("int");

                    b.Property<string>("TagLine")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("TeamPosition")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("Win")
                        .HasColumnType("bit");

                    b.HasKey("MatchId", "Puuid");

                    b.HasIndex("Puuid");

                    b.HasIndex("MatchId", "TeamId");

                    b.HasIndex("Puuid", "GameEndedInEarlySurrender");

                    b.ToTable("MatchParticipants");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.MatchRank", b =>
                {
                    b.Property<string>("MatchId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("RiotAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DivisionAfter")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("DivisionBefore")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<bool>("IsDemotion")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPromotion")
                        .HasColumnType("bit");

                    b.Property<int?>("LpAfter")
                        .HasColumnType("int");

                    b.Property<int?>("LpBefore")
                        .HasColumnType("int");

                    b.Property<int>("LpDelta")
                        .HasColumnType("int");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TierAfter")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("TierBefore")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("MatchId", "RiotAccountId");

                    b.HasIndex("RiotAccountId");

                    b.ToTable("MatchRanks");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.MatchRecording", b =>
                {
                    b.Property<string>("MatchId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("RiotAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AttachedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AttachedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("EventsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Privacy")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("YouTubeVideoId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("MatchId", "RiotAccountId");

                    b.HasIndex("AttachedByUserId");

                    b.HasIndex("RiotAccountId");

                    b.ToTable("MatchRecordings");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.PasswordReset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UserId", "RedeemedAt");

                    b.ToTable("PasswordResets");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.RankSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CapturedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Division")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int?>("LadderPosition")
                        .HasColumnType("int");

                    b.Property<int?>("LeaguePoints")
                        .HasColumnType("int");

                    b.Property<int?>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("MatchId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("RiotAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Tier")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("RiotAccountId", "QueueType", "CapturedAt", "Id");

                    b.ToTable("RankSnapshots");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.RankedSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPreseason")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("ResetsRank")
                        .HasColumnType("bit");

                    b.Property<long>("StartsAt")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StartsAt")
                        .IsUnique();

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeviceLabel")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.RetiredPuuid", b =>
                {
                    b.Property<Guid>("RiotAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Puuid")
                        .HasMaxLength(78)
                        .HasColumnType("nvarchar(78)");

                    b.Property<DateTimeOffset>("RetiredAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("RiotAccountId", "Puuid");

                    b.ToTable("RetiredPuuids");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.RiotAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("LinkedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int?>("ProfileIconId")
                        .HasColumnType("int");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasMaxLength(78)
                        .HasColumnType("nvarchar(78)");

                    b.Property<string>("RegionalRoute")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("SummonerId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("SummonerLevel")
                        .HasColumnType("bigint");

                    b.Property<string>("TagLine")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Puuid")
                        .IsUnique();

                    b.HasIndex("GameName", "TagLine")
                        .IsUnique();

                    b.ToTable("RiotAccounts");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.ServerSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Key");

                    b.ToTable("ServerSettings");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.SharedReplay", b =>
                {
                    b.Property<string>("MatchId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("BlobKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("ClaimedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<long?>("FileBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("GameVersion")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Patch")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset?>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MatchId");

                    b.HasIndex("UploadedAt");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("SharedReplays");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.SyncState", b =>
                {
                    b.Property<Guid>("RiotAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BackfillComplete")
                        .HasColumnType("bit");

                    b.Property<int>("BackfillTarget")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastDeltaSyncAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastFullSyncAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MostRecentMatchId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("RiotAccountId");

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.TelemetryRollup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("BucketStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Buckets")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("Instance")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Max")
                        .HasColumnType("float");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<double>("Min")
                        .HasColumnType("float");

                    b.Property<byte>("Resolution")
                        .HasColumnType("tinyint");

                    b.Property<double>("Sum")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Resolution", "Metric", "BucketStart");

                    b.HasIndex("Resolution", "BucketStart", "Metric", "Dimensions")
                        .IsUnique()
                        .HasDatabaseName("IX_TelemetryRollups_Hour")
                        .HasFilter("[Resolution] = 2");

                    b.ToTable("TelemetryRollups");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Foxfire.Data.Entities.ChampionMastery", b =>
                {
                    b.HasOne("Foxfire.Data.Entities.RiotAccount", "RiotAccount")
                        .WithMany()
                        .HasForeignKey("RiotAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiotAccount");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.Invite", b =>
                {
                    b.HasOne("Foxfire.Data.Entities.FoxfireUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Foxfire.Data.Entities.FoxfireUser", "RedeemedBy")
                        .WithMany()
                        .HasForeignKey("RedeemedByUserId");

                    b.Navigation("CreatedBy");

                    b.Navigation("RedeemedBy");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.LeagueEntry", b =>
                {
                    b.HasOne("Foxfire.Data.Entities.RiotAccount", "RiotAccount")
                        .WithMany()
                        .HasForeignKey("RiotAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiotAccount");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.MatchParticipant", b =>
                {
                    b.HasOne("Foxfire.Data.Entities.Match", "Match")
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.MatchRank", b =>
                {
                    b.HasOne("Foxfire.Data.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foxfire.Data.Entities.RiotAccount", "RiotAccount")
                        .WithMany()
                        .HasForeignKey("RiotAccountId")
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("RiotAccount");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.MatchRecording", b =>
                {
                    b.HasOne("Foxfire.Data.Entities.FoxfireUser", "AttachedBy")
                        .WithMany()
                        .HasForeignKey("AttachedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Foxfire.Data.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foxfire.Data.Entities.RiotAccount", "RiotAccount")
                        .WithMany()
                        .HasForeignKey("RiotAccountId")
                        .IsRequired();

                    b.Navigation("AttachedBy");

                    b.Navigation("Match");

                    b.Navigation("RiotAccount");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.PasswordReset", b =>
                {
                    b.HasOne("Foxfire.Data.Entities.FoxfireUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("Foxfire.Data.Entities.FoxfireUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.RankSnapshot", b =>
                {
                    b.HasOne("Foxfire.Data.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId");

                    b.HasOne("Foxfire.Data.Entities.RiotAccount", "RiotAccount")
                        .WithMany()
                        .HasForeignKey("RiotAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("RiotAccount");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("Foxfire.Data.Entities.FoxfireUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.RetiredPuuid", b =>
                {
                    b.HasOne("Foxfire.Data.Entities.RiotAccount", "RiotAccount")
                        .WithMany()
                        .HasForeignKey("RiotAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiotAccount");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.RiotAccount", b =>
                {
                    b.HasOne("Foxfire.Data.Entities.FoxfireUser", "Owner")
                        .WithMany("RiotAccounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.SharedReplay", b =>
                {
                    b.HasOne("Foxfire.Data.Entities.FoxfireUser", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.SyncState", b =>
                {
                    b.HasOne("Foxfire.Data.Entities.RiotAccount", "RiotAccount")
                        .WithMany()
                        .HasForeignKey("RiotAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiotAccount");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Foxfire.Data.Entities.FoxfireUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Foxfire.Data.Entities.FoxfireUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foxfire.Data.Entities.FoxfireUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Foxfire.Data.Entities.FoxfireUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Foxfire.Data.Entities.FoxfireUser", b =>
                {
                    b.Navigation("RiotAccounts");
                });

            modelBuilder.Entity("Foxfire.Data.Entities.Match", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
