namespace Foxfire.Core;

/// <summary>One day's close on the profile's rank graph.</summary>
/// <param name="At">
/// Where it is drawn: the end of its day, now − k·24h. Never the reading's own
/// time, which on a day with no games is days earlier.
/// </param>
/// <param name="Reading">A real reading, repeated onto the day it closed. Never an average.</param>
/// <param name="SeasonId">The season of the reading, which is where the line breaks.</param>
public sealed record RankTrendPoint(long At, RankReading Reading, int? SeasonId);

/// <summary>Thirty days of one queue, a close a day.</summary>
/// <param name="From">Where the window opens: thirty days back from <paramref name="To"/>, which is now.</param>
/// <param name="Points">Oldest first. A day with nothing to show is left out.</param>
/// <param name="NetLp">The ladder change over the window, from the raw readings. Null across a season change.</param>
public sealed record RankTrend(long From, long To, IReadOnlyList<RankTrendPoint> Points, int? NetLp);

/// <summary>Where somebody stood, as the net-change rule reads it.</summary>
public readonly record struct LadderMark(int? LadderPosition, int? SeasonId);

/// <summary>
/// The profile's rank graph: thirty days of one queue, thinned to a close a day.
/// A port of packages/core/src/rules/rankTrend.ts.
///
/// The Rank page reads every reading, which over a month is about one a ranked
/// game, and thins them to closes itself by the same rule. The profile draws the
/// same month 300px wide and needs nothing else, so it reads this instead: at
/// most 31 points, whatever the history holds.
///
/// Point k, for k = 30 down to 0, is drawn at now − k·24h and repeats the last
/// reading taken strictly before that moment — point 0 takes the latest of all,
/// including one a fast clock stamped after now. A day with no games therefore
/// repeats the day before, point 30 is the reading from before the window, and
/// nothing carries across a ladder reset: a day after one with no reading since
/// has no point.
///
/// fixtures/rank-trend-corpus.json is generated by the TypeScript and asserted
/// here by RankTrendCorpusTests, so the desktop's graph of its own database and
/// a server's graph of the same games cannot drift apart. Both sides are integer
/// arithmetic throughout, so there is no rounding to disagree about.
/// </summary>
public static class RankTrends
{
    /// <summary>How far back the window reaches.</summary>
    public const int Days = 30;

    private const long DayMs = 86_400_000L;

    /// <summary>Where the window opens: the moment point 30 is drawn at.</summary>
    public static long Since(long nowMs) => nowMs - (Days * DayMs);

    /// <summary>
    /// The ladder change over a window, or null where it would not mean anything.
    ///
    /// Counted from <paramref name="before"/> — the last reading ahead of the
    /// window — so a month's change includes its first game. Only inside one
    /// season: a reading from before a reset is not a place anyone lost LP from,
    /// so the count falls back to the first reading inside the window, and a
    /// window a reset runs through has no change at all.
    ///
    /// With nothing inside the window the change is zero from
    /// <paramref name="before"/>: a month without a ranked game moved nobody.
    /// </summary>
    /// <param name="window">The readings inside the window, oldest first.</param>
    public static int? NetChange(LadderMark? before, IReadOnlyList<LadderMark> window)
    {
        ArgumentNullException.ThrowIfNull(window);

        LadderMark? last = window.Count > 0 ? window[^1] : before;
        if (last is not { } end) return null;

        LadderMark? first = before is { } b && b.SeasonId == end.SeasonId
            ? b
            : window.Count > 0 ? window[0] : null;
        if (first is not { } start) return null;

        if (start.SeasonId != end.SeasonId) return null;
        if (start.LadderPosition is not { } from || end.LadderPosition is not { } to) return null;

        return to - from;
    }

    /// <summary>
    /// The trend of one queue's readings, which must be ordered as stored — by
    /// capturedAt, then by id — so two readings in the same millisecond keep
    /// their order. Never re-sorted here: List.Sort is not stable.
    /// </summary>
    public static RankTrend Of(IReadOnlyList<RankReading> readings, IReadOnlyList<Season> seasons, long nowMs)
    {
        ArgumentNullException.ThrowIfNull(readings);
        ArgumentNullException.ThrowIfNull(seasons);

        var since = Since(nowMs);
        int? SeasonOf(RankReading reading) => RankedSeasons.SeasonAt(seasons, reading.CapturedAt)?.Id;

        List<RankTrendPoint> points = [];
        var cursor = 0;
        RankReading? held = null;

        for (var k = Days; k >= 0; k--)
        {
            var at = nowMs - (k * DayMs);

            // Today's point is the latest reading of all; every earlier one is
            // the last reading taken strictly before its moment.
            while (cursor < readings.Count && (k == 0 || readings[cursor].CapturedAt < at))
            {
                held = readings[cursor];
                cursor++;
            }

            if (held is null || RankedSeasons.ResetsBetween(seasons, held.CapturedAt, at)) continue;

            points.Add(new RankTrendPoint(at, held, SeasonOf(held)));
        }

        // The change comes from the readings, not from the closes: two games on
        // the window's first day both count, where the closes see only the second.
        LadderMark? before = null;
        List<LadderMark> window = [];
        foreach (var reading in readings)
        {
            var mark = new LadderMark(reading.LadderPosition, SeasonOf(reading));
            if (reading.CapturedAt < since) before = mark;
            else window.Add(mark);
        }

        return new RankTrend(since, nowMs, points, NetChange(before, window));
    }
}
